CREATE SCHEMA PUBLIC;

CREATE TABLE PUBLIC.CATEGORIES ( 
	ID                   integer  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0BA30AFC_4FDC_4189_99B3_62C7CD900A98) NOT NULL,
	PARENT_ID            integer  DEFAULT 0 NOT NULL,
	NAME                 varchar(100)   NOT NULL,
	CONSTRAINT CONSTRAINT_6 PRIMARY KEY ( ID )
 );

CREATE TABLE PUBLIC.MANUFACTURERS ( 
	ID                   integer  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_D1F0A1C9_5F35_4CCA_92A3_5CF01436BC06) NOT NULL,
	NAME                 varchar(100)   NOT NULL,
	CONSTRAINT CONSTRAINT_8 PRIMARY KEY ( ID )
 );

CREATE TABLE PUBLIC.ITEMS ( 
	ID                   integer  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_AE6DC555_EF70_4416_849F_55190ACE1CD4) NOT NULL,
	NAME                 varchar(100)  DEFAULT '' NOT NULL,
	MODEL                varchar(100)  DEFAULT '' NOT NULL,
	MANUFACTURER_ID      integer   NOT NULL,
	PRICE                decimal(20)  DEFAULT 0 ,
	DESCRIPTION          varchar(500)  DEFAULT '' ,
	QUANTITY             integer  DEFAULT 0 ,
	CATEGORY_ID          integer   NOT NULL,
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY ( ID )
 );

CREATE INDEX IDX_ITEMS_CATEGORY_ID ON PUBLIC.ITEMS ( CATEGORY_ID );

CREATE INDEX IDX_ITEMS_MANUFACTURER_ID ON PUBLIC.ITEMS ( MANUFACTURER_ID );

ALTER TABLE PUBLIC.ITEMS ADD CONSTRAINT FK_ITEMS_CATEGORIES FOREIGN KEY ( CATEGORY_ID ) REFERENCES PUBLIC.CATEGORIES( ID ) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PUBLIC.ITEMS ADD CONSTRAINT FK_ITEMS_MANUFACTURERS FOREIGN KEY ( MANUFACTURER_ID ) REFERENCES PUBLIC.MANUFACTURERS( ID ) ON DELETE CASCADE ON UPDATE CASCADE;

